config/routes.rb
Rails.application.routes.draw do
  resources :keyword_entries
  resources :keywords
  resources :sites do
    collection { post :upload_csv }
  end

  root 'sites#index'
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :site
  has_many :keyword_entries, dependent: :destroy
end

app/models/keyword_collection.rb
class KeywordCollection < ActiveRecord::Base
  belongs_to :site

  def self.upload_csv(file)
    CSV.foreach(file.path, headers: true) do |row|
      KeywordCollection.create! row.to_hash
    end
  end
end

app/models/keyword_entry.rb
class KeywordEntry < ActiveRecord::Base
  belongs_to :keyword
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :keywords, dependent: :destroy
  has_many :keyword_entries, through: :keywords, dependent: :destroy

  accepts_nested_attributes_for :keywords, :keyword_entries

  def self.upload_csv(file)
    CSV.foreach(file.path,
      headers: true,
      col_sep: "\t",
      encoding: 'UTF-16LE:utf-8',
      header_converters: lambda { |h| h.downcase.gsub(' ', '_') }) do |row|

      site = find_by(name: row["site"]) || new
      site.name = row["site"]
      site.save!

      keyword = site.keywords.find_by(name: row["keyword"]) || site.keywords.build
      keyword.name = row["keyword"]
      keyword.save!

      keyword_entry = keyword.keyword_entries.find_by(date: row["date"] ||= row[0]) || keyword.keyword_entries.build
      keyword_entry.date = row["date"] ||= row[0]
      keyword_entry.google = row["google"]
      keyword_entry.google_base_rank = row["google_base_rank"]
      keyword_entry.yahoo = row["yahoo"]
      keyword_entry.bing = row["bing"]
      keyword_entry.global_monthly_searches = row["global_monthly_searches"]
      keyword_entry.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/keyword_entries_controller.rb
class KeywordEntriesController < ApplicationController
  before_action :set_keyword_entry, only: [:show, :edit, :update, :destroy]

  def index
    @keyword_entries = KeywordEntry.all
  end

  def create
    @keyword_entry = KeywordEntry.new(keyword_entry_params)

    respond_to do |format|
      if @keyword_entry.save
        format.html { redirect_to @keyword_entry, notice: 'Keyword entry was successfully created.' }
        format.json { render :show, status: :created, location: @keyword_entry }
      else
        format.html { render :new }
        format.json { render json: @keyword_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @keyword_entry.update(keyword_entry_params)
        format.html { redirect_to @keyword_entry, notice: 'Keyword entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword_entry }
      else
        format.html { render :edit }
        format.json { render json: @keyword_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @keyword_entry.destroy
    respond_to do |format|
      format.html { redirect_to keyword_entries_url, notice: 'Keyword entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_keyword_entry
      @keyword_entry = KeywordEntry.find(params[:id])
    end

    def keyword_entry_params
      params.require(:site).permit(:date, :google, :google_base_rank, :yahoo, :bing, :global_monthly_searches)
    end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]

  def index
    @keywords = Keyword.all
  end

  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: 'Keyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    def keyword_params
      params.require(:keyword).permit(:name)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  def index
    @sites = Site.all
  end

  def upload_csv
    Site.upload_csv(params[:file])
    redirect_to root_path, notice: 'CSV Uploaded'
  end

  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_site
      @site = Site.find(params[:id])
    end

    def site_params
      params.require(:site).permit(:name, keywords_attributes: [:name, :id, :site_id, keyword_entries_attributes: [:date, :google, :google_base_rank, :yahoo, :bing, :global_monthly_searches, :id, :keyword_id]])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/keyword_collections/_form.html.erb
<%= form_for(@keyword_collection) do |f| %>
  <% if @keyword_collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword_collection.errors.count, "error") %> prohibited this keyword_collection from being saved:</h2>

      <ul>
      <% @keyword_collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :site_id %><br>
    <%= f.text_field :site_id %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br>
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :google %><br>
    <%= f.number_field :google %>
  </div>
  <div class="field">
    <%= f.label :google_base_rank %><br>
    <%= f.number_field :google_base_rank %>
  </div>
  <div class="field">
    <%= f.label :yahoo %><br>
    <%= f.number_field :yahoo %>
  </div>
  <div class="field">
    <%= f.label :bing %><br>
    <%= f.number_field :bing %>
  </div>
  <div class="field">
    <%= f.label :global_monthly_searches %><br>
    <%= f.number_field :global_monthly_searches %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keyword_entries/index.html.erb
<h1>Listing Keyword Entries</h1>

<table>
  <thead>
    <tr>
      <th>Site</th>
      <th>Keywords</th>
      <th>Date</th>
      <th>Google</th>
      <th>Google base rank</th>
      <th>Yahoo</th>
      <th>Bing</th>
      <th>Global monthly searches</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @keyword_entries.each do |entry| %>
      <tr>
        <td><%= entry.keyword.site.name %></td>
        <td><%= entry.keyword.name %></td>
        <td><%= entry.date %></td>
        <td><%= entry.google %></td>
        <td><%= entry.google_base_rank %></td>
        <td><%= entry.yahoo %></td>
        <td><%= entry.bing %></td>
        <td><%= entry.global_monthly_searches %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/keywords/index.html.erb
<h1>Listing Keywords</h1>

<table>
  <thead>
    <tr>
      <th>Site</th>
      <th>Keywords</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><%= keyword.site.name %></td>
        <td><%= keyword.name %></td>
        <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsvVis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <p id="notice"><%= notice %></p>

    <nav class="main-nav flexbox margin-bottom-lg">
      <div class="flex-fill">
        <%= link_to "Sites", sites_path, class: "nav-link" %>
        <%= link_to "Keywords", keywords_path, class: "nav-link" %>
        <%= link_to "Entries", keyword_entries_path, class: "nav-link" %>
      </div>
      <div class="flex-auto">
        <%= form_tag upload_csv_sites_path, multipart: true, class: "upload-form" do %>
          <%= file_field_tag :file %>
          <%= submit_tag :upload_csv %>
        <% end %>
      </div>
    </nav>

  <%= yield %>

  </div>
</body>
</html>

app/views/sites/index.html.erb
<nav class="chart-nav flexbox margin-bottom">
  <div class="flex-fill">
    <a href="#" class="btn-blue active">Rank</a>
    <a href="#" class="btn-blue">Weighted Rank</a>
  </div>
  <div class="flex-auto">
    <a href="#" class="btn-blue">Last Week</a>
    <a href="#" class="btn-blue">Last 2 Weeks</a>
    <a href="#" class="btn-blue active">All Time</a>
  </div>
</nav>
<div class="js-line-chart"></div>

<%= javascript_include_tag "chart" %>

<!--
Add loading screen
Add legend
Improve graph display
Add details (tooltip) when hovering over data point
axis is doubled?
Add margin between axis
filter dates
transition rank / weighted rank
-->